[options]
admin_passwd = $pbkdf2-sha512$600000$5DyH0LrXmrMWgpBSai0FoA$BU/NKKWXuVKS5DrJSHl6nCvSvQwlfqZziPURMMlrNv8/BmFZfw6iWy6rzMoAnfeJAEsyy2rTiHYCEbETHPVCaw
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = cbs_new
dbfilter = ^cbs_new$
addons_path = /Users/nahabwebrian/personal/cbs_new/addons
xmlrpc_port = 8069
longpolling_port = False
list_db = False

